---
- name: Create a PostgreSQL container as a quadlet
  hosts: all
  gather_facts: true
  become: false

  handlers:

    - name: Restart the postgres service
      ansible.builtin.service:
        name: postgres.service
        state: restarted
        scope: user
        daemon_reload: true
      when:
        - not postgres_service_started.changed | bool

  tasks:

    - name: Create postgres volume
      containers.podman.podman_volume:
        state: quadlet
        name: postgres

    - name: Create Podman secret for the PostgreSQL password
      containers.podman.podman_secret:
        state: present
        name: postgres-password
        data: atotallysecurepasswordforpostgres

    - name: Create postgres container
      containers.podman.podman_container:
        state: quadlet
        name: postgres
        network: immich
        image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:41eacbe83eca995561fe43814fd4891e16e39632806253848efaf04d3c8a8b84
        label:
          app: immich
          traefik.enable: "false"
        env:
          POSTGRES_USER: immich
          POSTGRES_DB: immich
          POSTGRES_INITDB_ARGS: '--data-checksums'
        secrets:
          - postgres-password,type=env,target=POSTGRES_PASSWORD
        volumes:
          - 'postgres:/var/lib/postgresql/data:z'
        quadlet_options:
          - |
            [Unit]
            Description=Postgres container

            [Service]
            Restart=always

            [Install]
            WantedBy=default.target
      notify:
        - Restart the postgres service

    - name: Start the postgres service
      ansible.builtin.service:
        name: postgres.service
        state: started
        scope: user
        daemon_reload: true
      register: postgres_service_started

    - name: Enable the postgres service
      ansible.builtin.service:
        name: postgres.service
        enabled: true
        scope: user
        daemon_reload: true
